version: "3"

services:
  haskell_sandbox_pg:
    image: postgres
    ports:
      - "$POSTGRES_PORT:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
      TZ: UTC
    volumes:
      # - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      # - ./docker/postgres/dump:/dump

  # session_store:
  #   image: 'redis:latest'
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - './docker/session-store/data:/data'

  session_test_store:
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - "./docker/session-test-store/data:/data"
    profiles:
      - test
